package:
  name: oddt
  version: "0.1.5"

source:
  fn: oddt-0.1.5.tar.gz
  url: https://pypi.python.org/packages/source/o/oddt/oddt-0.1.5.tar.gz
  md5: 493f6710e0142490efd85340ba7f93b7
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - oddt = oddt:main
    #
    # Would create an entry point called oddt that calls oddt.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpydoc
    - numpy >=1.8
    - scipy >=0.13.0
    - scikit-learn >=0.13.0
    - ffnet >=0.7.1
    - joblib >=0.8
    - networkx >=1.3

  run:
    - python
    - numpydoc
    - numpy >=1.8
    - scipy >=0.13.0
    - scikit-learn >=0.13.0
    - ffnet >=0.7.1
    - joblib >=0.8
    - networkx >=1.3

test:
  # Python imports
  imports:
    - oddt

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/oddt/oddt
  license: BSD
  summary: 'Open Drug Discovery Toolkit'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
